name: Android template
on:
  workflow_dispatch:

  push:
    tags:
      - v3.42.4-capnm**

# Global settings.
env:
  GODOT_BASE_BRANCH: 3.2
  SCONS_CACHE_LIMIT: 2048
  V: 3.42.4.cannm1

jobs:
  android-template:
    runs-on: "ubuntu-20.04"

    name: Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v2

      # Azure repositories are not reliable, we need to prevent azure giving us packages.
      - name: Make apt sources.list use the default Ubuntu repositories
        run: |
          sudo rm -f /etc/apt/sources.list.d/*
          sudo cp -f misc/ci/sources.list /etc/apt/sources.list
          sudo apt-get update

      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      # Upload cache on completion and check it out now
      - name: Load .scons_cache directory
        id: android-template-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}

      # Use python 3.x release (works cross platform)
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      # See https://github.com/godotengine/godot-build-scripts/blob/master/build-android/build.sh
      - name: Compilation
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
          ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk-bundle
        run: |
          mkdir -p out/templates
          i="out/templates/info-android-template.txt"
          echo "Build commands:" > "${i}"

          c="scons -j2 verbose=yes platform=android target=release android_arch=armv7"
          echo "${c}" | tee -a "${i}"
          ${c}

          c="scons -j2 verbose=yes platform=android target=release android_arch=arm64v8"
          echo "${c}" | tee -a "${i}"
          ${c}

          c="scons -j2 verbose=yes platform=android target=release_debug android_arch=armv7"
          echo "${c}" | tee -a "${i}"
          ${c}

          c="scons -j2 verbose=yes platform=android target=release_debug android_arch=arm64v8"
          echo "${c}" | tee -a "${i}"
          ${c}

          pushd platform/android/java
          ./gradlew generateGodotTemplates
          popd

          echo "path: $(pwd)"
          ls -al
          echo '----' >> "${i}"
          ls -alh bin | tee -a "${i}"
          echo '----' >> "${i}"
          java -version 2>> "${i}"
          echo '----' >> "${i}"
          echo "GITHUB_REF: $GITHUB_REF" | tee -a "${i}"
          echo "GITHUB_SHA: $GITHUB_SHA" | tee -a "${i}"
          echo "$(git log -1)" | tee -a "${i}"

          echo "${V}" > out/templates/version.txt

          mv -v bin/android_debug.apk out/templates/
          mv -v bin/android_release.apk out/templates/

          mv -v bin/godot-lib.debug.aar out/templates/
          mv -v bin/godot-lib.release.aar out/templates/
          mv -v bin/android_source.zip out/templates/

      # Export artifact
      - uses: actions/upload-artifact@v2
        with:
          name: android-template
          path: out
